# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 358)
        MainWindow.setMinimumSize(QtCore.QSize(640, 358))
        MainWindow.setMaximumSize(QtCore.QSize(640, 358))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.texedit_Input = QtWidgets.QTextEdit(self.groupBox)
        self.texedit_Input.setObjectName("texedit_Input")
        self.gridLayout.addWidget(self.texedit_Input, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.texedit_Output = QtWidgets.QTextEdit(self.groupBox_2)
        self.texedit_Output.setObjectName("texedit_Output")
        self.gridLayout_2.addWidget(self.texedit_Output, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Code = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Code.setObjectName("btn_Code")
        self.verticalLayout.addWidget(self.btn_Code)
        self.btn_Decode = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decode.setObjectName("btn_Decode")
        self.verticalLayout.addWidget(self.btn_Decode)
        self.btn_Swip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Swip.setObjectName("btn_Swip")
        self.verticalLayout.addWidget(self.btn_Swip)
        self.btn_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Clear.setObjectName("btn_Clear")
        self.verticalLayout.addWidget(self.btn_Clear)
        self.btn_Close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Close.setObjectName("btn_Close")
        self.verticalLayout.addWidget(self.btn_Close)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_Close.clicked.connect(MainWindow.close)
        self.btn_Clear.clicked.connect(self.texedit_Input.clear)
        self.btn_Clear.clicked.connect(self.texedit_Output.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Six Rows"))
        self.groupBox.setTitle(_translate("MainWindow", "Ввод"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Вывод"))
        self.btn_Code.setText(_translate("MainWindow", "Кодировать"))
        self.btn_Decode.setText(_translate("MainWindow", "Декодировать"))
        self.btn_Swip.setText(_translate("MainWindow", "↑↓"))
        self.btn_Clear.setText(_translate("MainWindow", "Очистить"))
        self.btn_Close.setText(_translate("MainWindow", "Закрыть"))
